from __future__ import annotations

from pathlib import Path

import pytest
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect, text

from alembic import command
from blockwart import models  # noqa: F401
from blockwart.db.base import Base
from blockwart.db.migrations import (
    BASELINE_REVISION,
    PROJECT_ALEMBIC_CONFIG,
    DatabaseMigrationError,
    build_alembic_config,
    check_database_revision,
    upgrade_database,
)

HEAD_REVISION = "20260723_0002"


def _database_url(path: Path) -> str:
    return f"sqlite:///{path}"


def _revision(database_url: str) -> str | None:
    engine = create_engine(database_url)
    try:
        with engine.connect() as connection:
            row = connection.execute(text("SELECT version_num FROM alembic_version")).one_or_none()
            return None if row is None else str(row.version_num)
    finally:
        engine.dispose()


def test_real_alembic_upgrade_uses_runtime_database_url(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    runtime_path = tmp_path / "runtime.sqlite3"
    explicit_default_path = tmp_path / "must-not-be-used.sqlite3"
    monkeypatch.setenv("BLOCKWART_DATABASE_URL", _database_url(runtime_path))

    config = Config(str(PROJECT_ALEMBIC_CONFIG))
    config.set_main_option("sqlalchemy.url", _database_url(explicit_default_path))
    command.upgrade(config, "head")

    assert runtime_path.exists()
    assert not explicit_default_path.exists()
    assert _revision(_database_url(runtime_path)) == HEAD_REVISION


def test_explicit_database_url_overrides_runtime_environment(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    runtime_path = tmp_path / "runtime.sqlite3"
    explicit_path = tmp_path / "explicit.sqlite3"
    monkeypatch.setenv("BLOCKWART_DATABASE_URL", _database_url(runtime_path))

    command.upgrade(build_alembic_config(_database_url(explicit_path)), "head")

    assert explicit_path.exists()
    assert not runtime_path.exists()
    assert _revision(_database_url(explicit_path)) == HEAD_REVISION


def test_real_alembic_upgrade_creates_fresh_database_and_has_no_drift(
    tmp_path: Path,
) -> None:
    database_url = _database_url(tmp_path / "fresh.sqlite3")
    config = build_alembic_config(database_url)

    command.upgrade(config, "head")
    command.check(config)

    engine = create_engine(database_url)
    try:
        assert set(inspect(engine).get_table_names()) == {
            "alembic_version",
            "audit_events",
            "catalog_objects",
            "relationships",
        }
    finally:
        engine.dispose()
    assert set(Base.metadata.tables) == {
        "audit_events",
        "catalog_objects",
        "relationships",
    }
    assert _revision(database_url) == HEAD_REVISION


def test_upgrade_from_previous_real_revision_preserves_rows_and_json(
    tmp_path: Path,
) -> None:
    database_url = _database_url(tmp_path / "previous.sqlite3")
    config = build_alembic_config(database_url)
    command.upgrade(config, BASELINE_REVISION)

    engine = create_engine(database_url)
    unknown_json = '{"schema_version": 1, "future_field": {"keep": true}}'
    with engine.begin() as connection:
        connection.execute(
            text(
                "INSERT INTO catalog_objects "
                "(id, kind, label, status, summary, data_json) "
                "VALUES (:id, :kind, :label, :status, :summary, :data_json)"
            ),
            {
                "id": "legacy-system",
                "kind": "system",
                "label": "Legacy System",
                "status": "active",
                "summary": "Must survive.",
                "data_json": unknown_json,
            },
        )
        connection.execute(
            text(
                "INSERT INTO relationships (from_ref, relation_type, to_ref) "
                "VALUES ('system:legacy-system', 'depends_on', 'system:legacy-system')"
            )
        )
        connection.execute(
            text(
                "INSERT INTO audit_events (object_id, action, actor, summary) "
                "VALUES ('legacy-system', 'create', 'legacy', 'Must survive.')"
            )
        )

    command.upgrade(config, "head")

    with engine.connect() as connection:
        assert connection.execute(
            text("SELECT data_json FROM catalog_objects WHERE id = 'legacy-system'")
        ).scalar_one() == unknown_json
        assert connection.execute(text("SELECT count(*) FROM relationships")).scalar_one() == 1
        assert connection.execute(text("SELECT count(*) FROM audit_events")).scalar_one() == 1
    engine.dispose()
    assert check_database_revision(database_url) == HEAD_REVISION


def test_upgrade_adopts_only_matching_unversioned_legacy_database(
    tmp_path: Path,
) -> None:
    database_url = _database_url(tmp_path / "legacy.sqlite3")
    engine = create_engine(database_url)
    Base.metadata.create_all(engine)
    unknown_json = '{"schema_version": 1, "unknown_legacy_field": ["preserve"]}'
    with engine.begin() as connection:
        connection.execute(
            text(
                "INSERT INTO catalog_objects "
                "(id, kind, label, status, data_json) "
                "VALUES ('legacy', 'system', 'Legacy', 'active', :data_json)"
            ),
            {"data_json": unknown_json},
        )

    assert upgrade_database(database_url) == HEAD_REVISION

    with engine.connect() as connection:
        assert connection.execute(
            text("SELECT data_json FROM catalog_objects WHERE id = 'legacy'")
        ).scalar_one() == unknown_json
    engine.dispose()
    assert _revision(database_url) == HEAD_REVISION


def test_unversioned_schema_drift_fails_closed_without_stamping(
    tmp_path: Path,
) -> None:
    database_url = _database_url(tmp_path / "drifted-legacy.sqlite3")
    engine = create_engine(database_url)
    Base.metadata.create_all(engine)
    with engine.begin() as connection:
        connection.execute(text("DROP INDEX ix_catalog_objects_label"))

    with pytest.raises(
        DatabaseMigrationError,
        match="does not match the Blockwart baseline",
    ):
        upgrade_database(database_url)

    assert "alembic_version" not in inspect(engine).get_table_names()
    engine.dispose()


def test_alembic_check_detects_database_model_drift(tmp_path: Path) -> None:
    database_url = _database_url(tmp_path / "drift.sqlite3")
    config = build_alembic_config(database_url)
    command.upgrade(config, "head")

    engine = create_engine(database_url)
    with engine.begin() as connection:
        connection.execute(text("ALTER TABLE catalog_objects ADD COLUMN unexpected TEXT"))
    engine.dispose()

    with pytest.raises(AutogenerateDiffsDetected):
        command.check(config)


def test_wrong_database_target_aborts_with_redacted_error(tmp_path: Path) -> None:
    blocking_file = tmp_path / "not-a-directory"
    blocking_file.write_text("block", encoding="utf-8")
    database_url = _database_url(blocking_file / "blockwart.sqlite3")

    with pytest.raises(DatabaseMigrationError) as error:
        upgrade_database(database_url)

    assert str(error.value) == "Database migration failed"
    assert str(blocking_file) not in str(error.value)

    with pytest.raises(DatabaseMigrationError) as invalid_url_error:
        upgrade_database("not-a-database-url")

    assert str(invalid_url_error.value) == "Database migration failed"
    assert "not-a-database-url" not in str(invalid_url_error.value)


def test_revision_check_rejects_database_before_head(tmp_path: Path) -> None:
    database_url = _database_url(tmp_path / "old-revision.sqlite3")
    command.upgrade(build_alembic_config(database_url), BASELINE_REVISION)

    with pytest.raises(
        DatabaseMigrationError,
        match="revision does not match the application",
    ):
        check_database_revision(database_url)
