from __future__ import annotations

import json
import sqlite3
from pathlib import Path
from shutil import copytree

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import Column, Integer, Table, create_engine, inspect, text

from blockwart import models  # noqa: F401
from blockwart.db import migrations as migration_module
from blockwart.db.base import Base
from blockwart.db.migrations import (
    BASELINE_REVISION,
    DatabaseMigrationError,
    build_alembic_config,
    check_database_revision,
    upgrade_database,
)

PREVIOUS_HEAD_REVISION = "20260723_0002"
PLACEMENT_REVISION = "20260724_0003"
HEAD_REVISION = "20260724_0004"
PROJECT_ALEMBIC_CONFIG = Path(__file__).resolve().parents[1] / "alembic.ini"
LEGACY_SNAPSHOT = Path(__file__).resolve().parent / "fixtures" / "legacy_snapshot.sql"


def _database_url(path: Path) -> str:
    return f"sqlite:///{path}"


def _revision(database_url: str) -> str | None:
    engine = create_engine(database_url)
    try:
        with engine.connect() as connection:
            row = connection.execute(text("SELECT version_num FROM alembic_version")).one_or_none()
            return None if row is None else str(row.version_num)
    finally:
        engine.dispose()


def _create_unversioned_baseline(database_url: str) -> None:
    command.upgrade(build_alembic_config(database_url), BASELINE_REVISION)
    engine = create_engine(database_url)
    try:
        with engine.begin() as connection:
            connection.execute(text("DROP TABLE alembic_version"))
    finally:
        engine.dispose()


def _existing_data_snapshot(database_path: Path) -> dict[str, list[dict[str, object]]]:
    connection = sqlite3.connect(database_path)
    connection.row_factory = sqlite3.Row
    try:
        objects = []
        for row in connection.execute(
            "SELECT id, kind, label, status, summary, data_json, created_at, updated_at "
            "FROM catalog_objects ORDER BY id"
        ):
            payload = dict(row)
            payload["data_json"] = json.loads(str(payload["data_json"]))
            objects.append(payload)
        relationships = [
            dict(row)
            for row in connection.execute(
                "SELECT id, from_ref, relation_type, to_ref FROM relationships ORDER BY id"
            )
        ]
        audit_events = [
            dict(row)
            for row in connection.execute(
                "SELECT id, object_id, action, actor, summary, created_at "
                "FROM audit_events ORDER BY id"
            )
        ]
        return {
            "catalog_objects": objects,
            "relationships": relationships,
            "audit_events": audit_events,
        }
    finally:
        connection.close()


def test_real_alembic_upgrade_uses_runtime_database_url(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    runtime_path = tmp_path / "runtime.sqlite3"
    explicit_default_path = tmp_path / "must-not-be-used.sqlite3"
    monkeypatch.setenv("BLOCKWART_DATABASE_URL", _database_url(runtime_path))

    config = Config(str(PROJECT_ALEMBIC_CONFIG))
    config.set_main_option("sqlalchemy.url", _database_url(explicit_default_path))
    command.upgrade(config, "head")

    assert runtime_path.exists()
    assert not explicit_default_path.exists()
    assert _revision(_database_url(runtime_path)) == HEAD_REVISION


def test_explicit_database_url_overrides_runtime_environment(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    runtime_path = tmp_path / "runtime.sqlite3"
    explicit_path = tmp_path / "explicit.sqlite3"
    monkeypatch.setenv("BLOCKWART_DATABASE_URL", _database_url(runtime_path))

    command.upgrade(build_alembic_config(_database_url(explicit_path)), "head")

    assert explicit_path.exists()
    assert not runtime_path.exists()
    assert _revision(_database_url(explicit_path)) == HEAD_REVISION


def test_real_alembic_upgrade_creates_fresh_database_and_has_no_drift(
    tmp_path: Path,
) -> None:
    database_url = _database_url(tmp_path / "fresh.sqlite3")
    config = build_alembic_config(database_url)

    command.upgrade(config, "head")
    command.check(config)

    engine = create_engine(database_url)
    try:
        assert set(inspect(engine).get_table_names()) == {
            "alembic_version",
            "audit_events",
            "catalog_objects",
            "relationships",
        }
    finally:
        engine.dispose()
    assert set(Base.metadata.tables) == {
        "audit_events",
        "catalog_objects",
        "relationships",
    }
    assert _revision(database_url) == HEAD_REVISION


def test_upgrade_from_previous_real_revision_preserves_rows_and_json(
    tmp_path: Path,
) -> None:
    database_path = tmp_path / "previous.sqlite3"
    database_url = _database_url(database_path)
    config = build_alembic_config(database_url)
    command.upgrade(config, BASELINE_REVISION)

    connection = sqlite3.connect(database_path)
    try:
        connection.executescript(LEGACY_SNAPSHOT.read_text(encoding="utf-8"))
        connection.commit()
    finally:
        connection.close()
    before = _existing_data_snapshot(database_path)
    assert {row["kind"] for row in before["catalog_objects"]} == {
        "host",
        "system",
        "netzwerk",
        "service",
        "credential_reference",
        "runbook",
        "decision",
        "project",
    }
    system_before = next(
        row for row in before["catalog_objects"] if row["id"] == "legacy-system"
    )
    assert system_before["data_json"] == {
        "schema_version": 1,
        "future_field": {"keep": True},
        "tags": ["legacy", "future"],
    }

    command.upgrade(config, "head")

    after = _existing_data_snapshot(database_path)
    expected = json.loads(json.dumps(before))
    legacy_service = next(
        row for row in expected["catalog_objects"] if row["id"] == "legacy-service"
    )
    assert legacy_service["data_json"].pop("system_id") == "system:legacy-system"
    assert after == expected
    command.check(config)
    assert check_database_revision(database_url) == HEAD_REVISION


def test_canonical_placement_migration_converts_legacy_sources_losslessly(
    tmp_path: Path,
) -> None:
    database_path = tmp_path / "legacy-placement.sqlite3"
    database_url = _database_url(database_path)
    config = build_alembic_config(database_url)
    command.upgrade(config, PREVIOUS_HEAD_REVISION)

    connection = sqlite3.connect(database_path)
    try:
        connection.executemany(
            "INSERT INTO catalog_objects "
            "(id, kind, label, status, summary, data_json, created_at, updated_at) "
            "VALUES (?, ?, ?, 'active', ?, ?, ?, ?)",
            [
                (
                    "hardware",
                    "host",
                    "Hardware",
                    "physical",
                    '{"schema_version":1,"future":{"keep":true}}',
                    "2026-01-01 01:02:03",
                    "2026-02-02 02:03:04",
                ),
                (
                    "runtime",
                    "system",
                    "Runtime",
                    "runtime",
                    '{"schema_version":1,"runtime_type":"lxc"}',
                    "2026-01-01 01:02:03",
                    "2026-02-02 02:03:04",
                ),
                (
                    "runtime-api",
                    "service",
                    "Runtime API",
                    "service",
                    '{"schema_version":1,"system_id":"system:runtime",'
                    '"future":{"keep":["all","values"]}}',
                    "2026-01-01 01:02:03",
                    "2026-02-02 02:03:04",
                ),
                (
                    "hardware-console",
                    "service",
                    "Hardware Console",
                    "direct service",
                    '{"schema_version":1,"future":{"keep":"direct"}}',
                    "2026-01-01 01:02:03",
                    "2026-02-02 02:03:04",
                ),
            ],
        )
        connection.executemany(
            "INSERT INTO relationships (from_ref, relation_type, to_ref) "
            "VALUES (?, ?, ?)",
            [
                ("host:hardware", "hosts", "system:runtime"),
                ("system:runtime", "provides", "service:runtime-api"),
                ("host:hardware", "provides", "service:hardware-console"),
            ],
        )
        connection.commit()
    finally:
        connection.close()

    before = _existing_data_snapshot(database_path)
    command.upgrade(config, "head")
    after = _existing_data_snapshot(database_path)

    before_by_id = {row["id"]: row for row in before["catalog_objects"]}
    after_by_id = {row["id"]: row for row in after["catalog_objects"]}
    assert set(after_by_id) == set(before_by_id)
    for object_id, before_row in before_by_id.items():
        after_row = after_by_id[object_id]
        assert {
            key: value for key, value in after_row.items() if key != "data_json"
        } == {
            key: value for key, value in before_row.items() if key != "data_json"
        }
    assert after_by_id["runtime-api"]["data_json"] == {
        "schema_version": 1,
        "future": {"keep": ["all", "values"]},
    }
    assert after_by_id["hardware-console"]["data_json"] == {
        "schema_version": 1,
        "future": {"keep": "direct"},
    }
    assert [
        (row["from_ref"], row["relation_type"], row["to_ref"])
        for row in after["relationships"]
    ] == [
        ("host:hardware", "hosts", "system:runtime"),
        ("system:runtime", "hosts", "service:runtime-api"),
        ("host:hardware", "hosts", "service:hardware-console"),
    ]
    assert after["audit_events"] == before["audit_events"]
    assert _revision(database_url) == HEAD_REVISION


def test_canonical_placement_migration_rejects_conflicts_before_writing(
    tmp_path: Path,
) -> None:
    database_path = tmp_path / "conflicting-placement.sqlite3"
    database_url = _database_url(database_path)
    config = build_alembic_config(database_url)
    command.upgrade(config, PREVIOUS_HEAD_REVISION)
    connection = sqlite3.connect(database_path)
    try:
        connection.executemany(
            "INSERT INTO catalog_objects "
            "(id, kind, label, status, data_json) "
            "VALUES (?, ?, ?, 'active', ?)",
            [
                ("hardware", "host", "Hardware", '{"schema_version":1}'),
                ("runtime", "system", "Runtime", '{"schema_version":1}'),
                (
                    "api",
                    "service",
                    "API",
                    '{"schema_version":1,"system_id":"system:runtime"}',
                ),
            ],
        )
        connection.execute(
            "INSERT INTO relationships (from_ref, relation_type, to_ref) "
            "VALUES ('host:hardware', 'provides', 'service:api')"
        )
        connection.commit()
    finally:
        connection.close()
    before = _existing_data_snapshot(database_path)

    with pytest.raises(RuntimeError, match="multiple parents for service:api"):
        command.upgrade(config, "head")

    assert _existing_data_snapshot(database_path) == before
    assert _revision(database_url) == PREVIOUS_HEAD_REVISION


def test_relationship_integrity_migration_canonicalizes_dependencies_losslessly(
    tmp_path: Path,
) -> None:
    database_path = tmp_path / "legacy-dependencies.sqlite3"
    database_url = _database_url(database_path)
    config = build_alembic_config(database_url)
    command.upgrade(config, PLACEMENT_REVISION)

    connection = sqlite3.connect(database_path)
    try:
        connection.executemany(
            "INSERT INTO catalog_objects "
            "(id, kind, label, status, summary, data_json, created_at, updated_at) "
            "VALUES (?, ?, ?, 'active', ?, ?, ?, ?)",
            [
                (
                    "api",
                    "service",
                    "API",
                    "consumer",
                    '{"schema_version":1,"dependencies":'
                    '{"upstream":["service:database"],'
                    '"downstream":["service:worker"]},'
                    '"future":{"keep":["all","values"]}}',
                    "2026-01-01 01:02:03",
                    "2026-02-02 02:03:04",
                ),
                (
                    "database",
                    "service",
                    "Database",
                    "provider",
                    '{"schema_version":1}',
                    "2026-01-01 01:02:03",
                    "2026-02-02 02:03:04",
                ),
                (
                    "worker",
                    "service",
                    "Worker",
                    "consumer",
                    '{"schema_version":1,"dependencies":'
                    '{"upstream":["service:api"],"downstream":[]}}',
                    "2026-01-01 01:02:03",
                    "2026-02-02 02:03:04",
                ),
            ],
        )
        connection.execute(
            "INSERT INTO relationships (from_ref, relation_type, to_ref) "
            "VALUES ('service:api', 'depends_on', 'service:database')"
        )
        connection.commit()
    finally:
        connection.close()

    before = _existing_data_snapshot(database_path)
    command.upgrade(config, "head")
    after = _existing_data_snapshot(database_path)

    assert {
        (row["from_ref"], row["relation_type"], row["to_ref"])
        for row in after["relationships"]
    } == {
        ("service:api", "depends_on", "service:database"),
        ("service:worker", "depends_on", "service:api"),
    }
    before_by_id = {row["id"]: row for row in before["catalog_objects"]}
    after_by_id = {row["id"]: row for row in after["catalog_objects"]}
    for object_id, before_row in before_by_id.items():
        after_row = after_by_id[object_id]
        assert {
            key: value for key, value in after_row.items() if key != "data_json"
        } == {
            key: value for key, value in before_row.items() if key != "data_json"
        }
        expected_data = dict(before_row["data_json"])
        expected_data.pop("dependencies", None)
        assert after_row["data_json"] == expected_data
    assert after["audit_events"] == before["audit_events"]
    assert _revision(database_url) == HEAD_REVISION


def test_relationship_integrity_migration_rejects_invalid_data_before_writing(
    tmp_path: Path,
) -> None:
    database_path = tmp_path / "invalid-relationship.sqlite3"
    database_url = _database_url(database_path)
    config = build_alembic_config(database_url)
    command.upgrade(config, PLACEMENT_REVISION)

    connection = sqlite3.connect(database_path)
    try:
        connection.executemany(
            "INSERT INTO catalog_objects "
            "(id, kind, label, status, data_json) "
            "VALUES (?, 'system', ?, 'active', '{\"schema_version\":1}')",
            [("runtime-a", "Runtime A"), ("runtime-b", "Runtime B")],
        )
        connection.execute(
            "INSERT INTO relationships (from_ref, relation_type, to_ref) "
            "VALUES ('system:runtime-a', 'hosts', 'system:runtime-b')"
        )
        connection.commit()
    finally:
        connection.close()
    before = _existing_data_snapshot(database_path)

    with pytest.raises(RuntimeError, match="invalid relationship direction"):
        command.upgrade(config, "head")

    assert _existing_data_snapshot(database_path) == before
    assert _revision(database_url) == PLACEMENT_REVISION


def test_relationship_database_constraints_reject_bypass_writes(
    tmp_path: Path,
) -> None:
    database_path = tmp_path / "relationship-constraints.sqlite3"
    database_url = _database_url(database_path)
    config = build_alembic_config(database_url)
    command.upgrade(config, "head")

    connection = sqlite3.connect(database_path)
    try:
        connection.executemany(
            "INSERT INTO catalog_objects "
            "(id, kind, label, status, data_json) VALUES (?, ?, ?, 'active', '{}')",
            [
                ("hardware-a", "host", "Hardware A"),
                ("hardware-b", "host", "Hardware B"),
                ("api", "service", "API"),
                ("worker", "service", "Worker"),
            ],
        )
        connection.execute(
            "INSERT INTO relationships (from_ref, relation_type, to_ref) "
            "VALUES ('host:hardware-a', 'hosts', 'service:api')"
        )
        connection.commit()

        invalid_statements = [
            (
                "INSERT INTO relationships (from_ref, relation_type, to_ref) "
                "VALUES ('host:hardware-a', 'hosts', 'service:api')"
            ),
            (
                "INSERT INTO relationships (from_ref, relation_type, to_ref) "
                "VALUES ('service:api', 'depends_on', 'service:api')"
            ),
            (
                "INSERT INTO relationships (from_ref, relation_type, to_ref) "
                "VALUES ('service:api', 'unknown', 'service:worker')"
            ),
            (
                "INSERT INTO relationships (from_ref, relation_type, to_ref) "
                "VALUES ('host:hardware-b', 'hosts', 'service:api')"
            ),
        ]
        for statement in invalid_statements:
            with pytest.raises(sqlite3.IntegrityError):
                connection.execute(statement)
            connection.rollback()
    finally:
        connection.close()


def test_upgrade_adopts_only_matching_unversioned_legacy_database(
    tmp_path: Path,
) -> None:
    database_url = _database_url(tmp_path / "legacy.sqlite3")
    _create_unversioned_baseline(database_url)
    engine = create_engine(database_url)
    unknown_json = '{"schema_version": 1, "unknown_legacy_field": ["preserve"]}'
    with engine.begin() as connection:
        connection.execute(
            text(
                "INSERT INTO catalog_objects "
                "(id, kind, label, status, data_json) "
                "VALUES ('legacy', 'system', 'Legacy', 'active', :data_json)"
            ),
            {"data_json": unknown_json},
        )

    assert upgrade_database(database_url) == HEAD_REVISION

    with engine.connect() as connection:
        assert connection.execute(
            text("SELECT data_json FROM catalog_objects WHERE id = 'legacy'")
        ).scalar_one() == unknown_json
    engine.dispose()
    assert _revision(database_url) == HEAD_REVISION


def test_unversioned_schema_drift_fails_closed_without_stamping(
    tmp_path: Path,
) -> None:
    database_url = _database_url(tmp_path / "drifted-legacy.sqlite3")
    _create_unversioned_baseline(database_url)
    engine = create_engine(database_url)
    with engine.begin() as connection:
        connection.execute(text("DROP INDEX ix_catalog_objects_label"))

    with pytest.raises(
        DatabaseMigrationError,
        match="does not match the Blockwart baseline",
    ):
        upgrade_database(database_url)

    assert "alembic_version" not in inspect(engine).get_table_names()
    engine.dispose()


def test_unversioned_baseline_adopts_before_real_future_migration(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    migrations_dir = tmp_path / "migrations"
    copytree(migration_module.MIGRATIONS_DIR, migrations_dir)
    future_revision = "20990101_0003"
    (migrations_dir / "versions" / f"{future_revision}_future_table.py").write_text(
        f'''"""synthetic future migration for the baseline-adoption contract"""

import sqlalchemy as sa
from alembic import op

revision = "{future_revision}"
down_revision = "{HEAD_REVISION}"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "future_head_only",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    op.drop_table("future_head_only")
''',
        encoding="utf-8",
    )
    monkeypatch.setattr(migration_module, "MIGRATIONS_DIR", migrations_dir)

    database_url = _database_url(tmp_path / "future-upgrade.sqlite3")
    _create_unversioned_baseline(database_url)
    engine = create_engine(database_url)
    with engine.begin() as connection:
        connection.execute(
            text(
                "INSERT INTO catalog_objects "
                "(id, kind, label, status, data_json) "
                "VALUES ('legacy', 'system', 'Legacy', 'active', '{}')"
            )
        )

    future_table = Table(
        "future_head_only",
        Base.metadata,
        Column("id", Integer, primary_key=True),
    )
    try:
        assert upgrade_database(database_url) == future_revision
        assert set(inspect(engine).get_table_names()) == {
            "alembic_version",
            "audit_events",
            "catalog_objects",
            "future_head_only",
            "relationships",
        }
        with engine.connect() as connection:
            assert connection.execute(
                text("SELECT label FROM catalog_objects WHERE id = 'legacy'")
            ).scalar_one() == "Legacy"
        assert _revision(database_url) == future_revision
    finally:
        Base.metadata.remove(future_table)
        engine.dispose()


def test_alembic_check_detects_database_model_drift(tmp_path: Path) -> None:
    database_url = _database_url(tmp_path / "drift.sqlite3")
    config = build_alembic_config(database_url)
    command.upgrade(config, "head")

    engine = create_engine(database_url)
    with engine.begin() as connection:
        connection.execute(text("ALTER TABLE catalog_objects ADD COLUMN unexpected TEXT"))
    engine.dispose()

    with pytest.raises(AutogenerateDiffsDetected):
        command.check(config)


def test_wrong_database_target_aborts_with_redacted_error(tmp_path: Path) -> None:
    blocking_file = tmp_path / "not-a-directory"
    blocking_file.write_text("block", encoding="utf-8")
    database_url = _database_url(blocking_file / "blockwart.sqlite3")

    with pytest.raises(DatabaseMigrationError) as error:
        upgrade_database(database_url)

    assert str(error.value) == "Database migration failed"
    assert str(blocking_file) not in str(error.value)

    with pytest.raises(DatabaseMigrationError) as invalid_url_error:
        upgrade_database("not-a-database-url")

    assert str(invalid_url_error.value) == "Database migration failed"
    assert "not-a-database-url" not in str(invalid_url_error.value)


def test_revision_check_rejects_database_before_head(tmp_path: Path) -> None:
    database_url = _database_url(tmp_path / "old-revision.sqlite3")
    command.upgrade(build_alembic_config(database_url), BASELINE_REVISION)

    with pytest.raises(
        DatabaseMigrationError,
        match="revision does not match the application",
    ):
        check_database_revision(database_url)
