from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path
from shutil import copy2

SCRIPT_SOURCE = Path(__file__).resolve().parents[1] / "scripts/update-dependency-locks.sh"
HEADER = """\
# Generated by scripts/update-dependency-locks.sh.
# Python 3.12 / Linux / pip-tools 7.6.0.
# Do not edit manually; see docs/ci.md.

"""


def _lock(pin: str = "1.4.0", *, removed: bool = False) -> str:
    body = f"starlette=={pin}\n    # via blockwart (pyproject.toml)\n"
    if removed:
        body += "unused-package==1.0.0\n    # via blockwart (pyproject.toml)\n"
    return HEADER + body


def _write_fake_python(path: Path) -> None:
    path.write_text(
        """#!/usr/bin/env python3
import json
import os
from pathlib import Path
import re
import sys

if sys.argv[1:2] == ["-c"]:
    print("7.6.0")
    raise SystemExit(0)

args = sys.argv[1:]
if args[:3] != ["-m", "piptools", "compile"]:
    raise SystemExit(f"unexpected invocation: {args!r}")

compile_args = args[3:]
output_path = Path(compile_args[compile_args.index("--output-file") + 1])
project_path = Path(compile_args[-1])
seed = output_path.read_text() if output_path.exists() else ""
flags = [flag for flag in ("--upgrade", "--no-upgrade") if flag in compile_args]
if len(flags) != 1:
    raise SystemExit(f"expected exactly one upgrade mode, found {flags!r}")

flag = flags[0]
if flag == "--upgrade" and seed:
    raise SystemExit("update compilation was seeded")
if flag == "--no-upgrade" and not seed:
    raise SystemExit("check compilation was not seeded")

match = re.search(r"^starlette==([^\\s]+)$", seed, re.MULTILINE)
scenario = os.environ["FAKE_RESOLVER_SCENARIO"]
if flag == "--upgrade" or scenario == "incompatible":
    pin = "1.4.1"
else:
    pin = match.group(1) if match else "1.4.1"

body = f"starlette=={pin}\\n    # via blockwart ({project_path})\\n"
output_path.write_text(body)

event = {
    "extra": "dev" if "--extra" in compile_args else "runtime",
    "flag": flag,
    "seeded": bool(seed),
    "seed_pin": match.group(1) if match else None,
    "scenario": scenario,
}
with Path(os.environ["FAKE_RESOLVER_LOG"]).open("a") as log:
    log.write(json.dumps(event, sort_keys=True) + "\\n")
"""
    )
    path.chmod(0o755)


def _miniature_project(
    tmp_path: Path,
    *,
    runtime_lock: str | None = None,
    dev_lock: str | None = None,
) -> tuple[Path, Path, Path]:
    project = tmp_path / "project"
    scripts = project / "scripts"
    requirements = project / "requirements"
    scripts.mkdir(parents=True)
    requirements.mkdir()
    copy2(SCRIPT_SOURCE, scripts / SCRIPT_SOURCE.name)
    (project / "pyproject.toml").write_text(
        """\
[project]
name = "blockwart"
version = "0"
dependencies = ["starlette>=1"]

[project.optional-dependencies]
dev = ["starlette>=1"]
"""
    )
    if runtime_lock is not None:
        (requirements / "runtime.txt").write_text(runtime_lock)
    if dev_lock is not None:
        (requirements / "dev.txt").write_text(dev_lock)

    fake_python = tmp_path / "fake-python"
    resolver_log = tmp_path / "resolver.jsonl"
    _write_fake_python(fake_python)
    return project, fake_python, resolver_log


def _snapshot(project: Path) -> dict[str, bytes]:
    return {
        str(path.relative_to(project)): path.read_bytes()
        for path in sorted(project.rglob("*"))
        if path.is_file()
    }


def _run(
    project: Path,
    fake_python: Path,
    resolver_log: Path,
    scenario: str,
    *args: str,
) -> subprocess.CompletedProcess[str]:
    env = os.environ.copy()
    env.update(
        {
            "PYTHON_BIN": str(fake_python),
            "FAKE_RESOLVER_LOG": str(resolver_log),
            "FAKE_RESOLVER_SCENARIO": scenario,
        }
    )
    return subprocess.run(
        [str(project / "scripts/update-dependency-locks.sh"), *args],
        cwd=project,
        env=env,
        text=True,
        capture_output=True,
        check=False,
    )


def _events(resolver_log: Path) -> list[dict[str, object]]:
    return [json.loads(line) for line in resolver_log.read_text().splitlines()]


def test_check_retains_compatible_pins_and_never_writes_project(tmp_path: Path) -> None:
    committed_lock = _lock()
    project, fake_python, resolver_log = _miniature_project(
        tmp_path,
        runtime_lock=committed_lock,
        dev_lock=committed_lock,
    )
    before = _snapshot(project)

    completed = _run(project, fake_python, resolver_log, "compatible-newer", "--check")

    assert completed.returncode == 0, completed.stderr
    assert completed.stdout == "dependency_locks=up_to_date\n"
    assert _snapshot(project) == before
    assert _events(resolver_log) == [
        {
            "extra": "runtime",
            "flag": "--no-upgrade",
            "scenario": "compatible-newer",
            "seed_pin": "1.4.0",
            "seeded": True,
        },
        {
            "extra": "dev",
            "flag": "--no-upgrade",
            "scenario": "compatible-newer",
            "seed_pin": "1.4.0",
            "seeded": True,
        },
    ]


def test_check_fails_when_a_stale_package_is_removed(tmp_path: Path) -> None:
    stale_lock = _lock(removed=True)
    project, fake_python, resolver_log = _miniature_project(
        tmp_path,
        runtime_lock=stale_lock,
        dev_lock=stale_lock,
    )
    before = _snapshot(project)

    completed = _run(project, fake_python, resolver_log, "removed", "--check")

    assert completed.returncode != 0
    assert _snapshot(project) == before


def test_check_fails_closed_when_a_committed_lock_is_missing(tmp_path: Path) -> None:
    project, fake_python, resolver_log = _miniature_project(
        tmp_path,
        runtime_lock=None,
        dev_lock=_lock(),
    )
    before = _snapshot(project)

    completed = _run(project, fake_python, resolver_log, "compatible-newer", "--check")

    assert completed.returncode != 0
    assert _snapshot(project) == before
    assert not resolver_log.exists()


def test_check_fails_when_committed_pin_becomes_incompatible(tmp_path: Path) -> None:
    committed_lock = _lock()
    project, fake_python, resolver_log = _miniature_project(
        tmp_path,
        runtime_lock=committed_lock,
        dev_lock=committed_lock,
    )
    before = _snapshot(project)

    completed = _run(project, fake_python, resolver_log, "incompatible", "--check")

    assert completed.returncode != 0
    assert _snapshot(project) == before


def test_update_is_unseeded_and_upgrades_both_locks(tmp_path: Path) -> None:
    committed_lock = _lock()
    project, fake_python, resolver_log = _miniature_project(
        tmp_path,
        runtime_lock=committed_lock,
        dev_lock=committed_lock,
    )

    completed = _run(project, fake_python, resolver_log, "compatible-newer")

    assert completed.returncode == 0, completed.stderr
    assert completed.stdout == "dependency_locks=updated\n"
    expected_lock = _lock("1.4.1")
    assert (project / "requirements/runtime.txt").read_text() == expected_lock
    assert (project / "requirements/dev.txt").read_text() == expected_lock
    assert _events(resolver_log) == [
        {
            "extra": "runtime",
            "flag": "--upgrade",
            "scenario": "compatible-newer",
            "seed_pin": None,
            "seeded": False,
        },
        {
            "extra": "dev",
            "flag": "--upgrade",
            "scenario": "compatible-newer",
            "seed_pin": None,
            "seeded": False,
        },
    ]
