#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
PYTHON_BIN=${PYTHON_BIN:-python3}
EXPECTED_PIP_TOOLS_VERSION=7.6.0
MODE=${1:-update}

if [[ "$MODE" != update && "$MODE" != --check ]]; then
  echo "usage: $0 [--check]" >&2
  exit 2
fi

ACTUAL_PIP_TOOLS_VERSION=$(
  "$PYTHON_BIN" -c 'from importlib.metadata import version; print(version("pip-tools"))'
)
if [[ "$ACTUAL_PIP_TOOLS_VERSION" != "$EXPECTED_PIP_TOOLS_VERSION" ]]; then
  echo "pip-tools $EXPECTED_PIP_TOOLS_VERSION is required; found $ACTUAL_PIP_TOOLS_VERSION" >&2
  exit 1
fi

TEMP_DIR=$(mktemp -d)
cleanup() {
  find "$TEMP_DIR" -mindepth 1 -delete
  rmdir "$TEMP_DIR"
}
trap cleanup EXIT

compile_lock() {
  local extra=$1
  local output=$2
  local body="$TEMP_DIR/$(basename "$output").body"
  local -a extra_args=()
  if [[ -n "$extra" ]]; then
    extra_args=(--extra "$extra")
  fi

  "$PYTHON_BIN" -m piptools compile \
    --allow-unsafe \
    --no-header \
    --resolver backtracking \
    --strip-extras \
    --quiet \
    "${extra_args[@]}" \
    --output-file "$body" \
    "$PROJECT_ROOT/pyproject.toml"

  {
    echo "# Generated by scripts/update-dependency-locks.sh."
    echo "# Python 3.12 / Linux / pip-tools $EXPECTED_PIP_TOOLS_VERSION."
    echo "# Do not edit manually; see docs/ci.md."
    echo
    sed "s#${PROJECT_ROOT}/pyproject.toml#pyproject.toml#g" "$body"
  } >"$output"
}

if [[ "$MODE" == --check ]]; then
  compile_lock "" "$TEMP_DIR/runtime.txt"
  compile_lock dev "$TEMP_DIR/dev.txt"
  cmp "$TEMP_DIR/runtime.txt" "$PROJECT_ROOT/requirements/runtime.txt"
  cmp "$TEMP_DIR/dev.txt" "$PROJECT_ROOT/requirements/dev.txt"
  echo "dependency_locks=up_to_date"
  exit 0
fi

mkdir -p "$PROJECT_ROOT/requirements"
compile_lock "" "$PROJECT_ROOT/requirements/runtime.txt"
compile_lock dev "$PROJECT_ROOT/requirements/dev.txt"
echo "dependency_locks=updated"
